# Generated by Django 5.2.3 on 2025-06-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='barber_photos/')),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('skills', models.TextField()),
                ('reviews', models.TextField()),
                ('services', models.ManyToManyField(related_name='barbers', to='service.service')),
            ],
        ),
    ]
