# Generated by Django 5.2.3 on 2025-06-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberinfo',
            name='bio',
            field=models.TextField(default='no bios yet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barberinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='barber_photos/'),
        ),
        migrations.AddField(
            model_name='barberinfo',
            name='reviews',
            field=models.TextField(default='no reviews yet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barberinfo',
            name='services',
            field=models.ManyToManyField(related_name='barbers', to='service.service'),
        ),
        migrations.AddField(
            model_name='barberinfo',
            name='skills',
            field=models.TextField(default='no skills yet'),
            preserve_default=False,
        ),
    ]
