# Generated by Django 5.2.3 on 2025-06-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.CharField(default='no price', max_length=100),
            preserve_default=False,
        ),
    ]
